Two typos in soe-cleanup.sh
First: Missing 'test' command in the if. Fixing:

./soe-cleanup.sh: line 7: -f: command not found

Second: If org have whitespace in the name, this breaks. Fixing:

Error: too many arguments

See: 'hammer content-view list --help'